const fs = require('fs');
const NEW_ENTRIES = [
  { english: "what is going on", garo: "Maia Kosak-o re·angenga maia?", category: "phrases" },
  { english: "i need your help", garo: "Anga nang·ni dakchakaniko nanga", category: "phrases" },
  { english: "i thought it was you", garo: "Angade na·akon inesa chanchiachim", category: "phrases" },
  { english: "i work hard", garo: "Anga rake kam ka·a", category: "phrases" },
  { english: "i'm waiting", garo: "Anga sengenga", category: "phrases" },
  { english: "is it good", garo: "Namama?", category: "phrases" },
  { english: "people say it's good is it good", garo: "Manderang aganna nama ine, namama?", category: "phrases" },
  { english: "must be inside", garo: "Ning·on ong·na nanga", category: "phrases" },
  { english: "are you busy", garo: "Jakchakjaengama?", category: "phrases" },
  { english: "are you having fun", garo: "An·sengenga ma?", category: "phrases" },
  { english: "are you sleeping", garo: "Na·a tuengama?", category: "phrases" },
  { english: "in a broad daylight are you sleeping", garo: "Salmatraktrak-o na·a tuengama?", category: "phrases" },
  { english: "are you taken", garo: "Na·a sakoba ka·a dongama?", category: "phrases" },
  { english: "are you guys coming", garo: "Na·simang re·baengama?", category: "phrases" },
  { english: "are you hungry", garo: "Okkriengama?", category: "phrases" },
  { english: "this is an awkward thing to see", garo: "Ia nina nitoja", category: "phrases" },
  { english: "this house color is brown", garo: "Ia nok ni rong gitchakmrang ong.a", category: "phrases" },
  { english: "bye i'm going", garo: "De/Ra/Bai anga re·angengjok", category: "phrases" },
  { english: "sleep on the carpet", garo: "Amo tusibo", category: "phrases" },
  { english: "their conversation is very nice", garo: "Uamangni agangrikani namen nambea", category: "phrases" },
  { english: "our country is big", garo: "An.chingni a.song dala", category: "phrases" },
  { english: "do you have a boyfriend", garo: "Nangni mikchagipa dong.a ma?", category: "phrases" },
  { english: "do you know english", garo: "Na·a inglis man·ama?", category: "phrases" },
  { english: "do you know hindi", garo: "Na·a Hindi man·ama?", category: "phrases" },
  { english: "do you know me", garo: "Na·a angko ma·siama?", category: "phrases" },
  { english: "do you play games", garo: "Na·a gamerangko kal·ama?", category: "phrases" },
  { english: "do you use whatsapp", garo: "Na·a whatsapp jakkalama?", category: "phrases" },
  { english: "i need to sleep early tonight", garo: "Ang.a da.al atamo seng.gnang tusina nang.a", category: "phrases" },
  { english: "last year we went to balpakram", garo: "Da·sikkari chinga Balpakram re·anga", category: "phrases" },
  { english: "why do you laugh", garo: "Maina na·a ka·dinga?", category: "phrases" },
  { english: "a lot of mosquitoes in here", garo: "Ganggu bang·bea iano", category: "phrases" },
  { english: "no way ahead", garo: "Mikkangchi rama gri/dongja", category: "phrases" },
  { english: "now what", garo: "Da·ode maia?", category: "phrases" },
  { english: "nowadays it's hot", garo: "Da·ororode ding·a", category: "phrases" },
  { english: "our home is far", garo: "Chingni nok chela", category: "phrases" },
  { english: "our language", garo: "An·chingni ku·sik", category: "phrases" },
  { english: "pair of shoes", garo: "Juta jorasa", category: "phrases" },
  { english: "praise the lord", garo: "Gitel na rasong", category: "church" },
  { english: "bring me the rice powder", garo: "Angna pura ra·ba", category: "food" },
  { english: "this room is big", garo: "Ia kuturi dala", category: "phrases" },
  { english: "are you scared", garo: "Ma na·a kenenga?", category: "phrases" },
  { english: "you really are shameless", garo: "Aai na·ade mikgil gri bebemo", category: "phrases" },
  { english: "shut up", garo: "Jrip!", category: "phrases" },
  { english: "their house is very beautiful", garo: "Uamang ni nok namen netobea", category: "phrases" },
  { english: "what's the time", garo: "Mai somoi / baji?", category: "phrases" },
  { english: "we will work today", garo: "Chinga da.alo kam kagen", category: "phrases" },
  { english: "drink some tea", garo: "Cha on·tisa ringbo", category: "food" },
  { english: "he told me", garo: "Bia angna agana", category: "phrases" },
  { english: "he told me about you", garo: "Bia nang·ni gimin angna agana", category: "phrases" },
  { english: "i made a mistake", garo: "Anga ong·gija dakaha", category: "phrases" },
  { english: "i saw a bird in the tree", garo: "Anga bol-o do·o-ko nikaha", category: "phrases" },
  { english: "i speak to him", garo: "Anga una agana", category: "phrases" },
  { english: "i wash the dishes", garo: "Anga bostu su·gala", category: "phrases" },
  { english: "have you eaten breakfast", garo: "Naa nastha chaa ha ma?", category: "food" },
  { english: "have you eaten rice", garo: "Mi cha·jok ma?", category: "food" },
  { english: "clouds are dark", garo: "Aramrang gisima", category: "phrases" },
  { english: "no electricity", garo: "Karen dongja", category: "phrases" },
  { english: "you're first", garo: "Na·an skang", category: "phrases" },
  { english: "you're lying", garo: "Na·a tol·enga", category: "phrases" },
  { english: "you're welcome", garo: "Mamingba ong·ja", category: "phrases" },
  { english: "no need to thank me you're welcome", garo: "Mamingba ong·ja, angko mittelna nangjawa", category: "phrases" },
  { english: "your feet stinks", garo: "Nangni ja'a senga", category: "phrases" },
  { english: "stop it", garo: "Iako dondipbo", category: "phrases" },
  { english: "this goat kid is ours", garo: "Ia dobok bisa chingni ong.a", category: "animals" },
  { english: "about you and about her", garo: "Nang·nigimin aro binigimin", category: "phrases" },
  { english: "joking", garo: "Ka·lakenga", category: "phrases" },
  { english: "job", garo: "Kam", category: "business" },
  { english: "what job do you do", garo: "Na·ara mai kamko ka·a?", category: "business" },
  { english: "abandon", garo: "Watgala", category: "verbs" },
  { english: "abnormal", garo: "Ong'ronggijagipa", category: "uncategorized" },
  { english: "about", garo: "Gimin", category: "uncategorized" },
  { english: "and", garo: "Aro", category: "uncategorized" },
  { english: "ask", garo: "Sing·a", category: "verbs" },
  { english: "at", garo: "O", category: "uncategorized" },
  { english: "ate", garo: "Cha·aha", category: "food" },
  { english: "awesome", garo: "Gasua", category: "phrases" },
  { english: "awkward", garo: "Nitoja", category: "uncategorized" },
  { english: "backward", garo: "Bikpile", category: "uncategorized" },
  { english: "backbone", garo: "Jangil bolgro", category: "health" },
  { english: "basically", garo: "Chong.motan", category: "uncategorized" },
  { english: "bath", garo: "Aua", category: "health" },
  { english: "be happy", garo: "Kusi ong.bo", category: "phrases" },
  { english: "beautiful", garo: "Sila", category: "uncategorized" },
  { english: "beef", garo: "Matchu be·en", category: "food" },
  { english: "bright", garo: "Ching'a", category: "uncategorized" },
  { english: "brown", garo: "Gitchakmrang", category: "uncategorized" },
  { english: "bye", garo: "De / Ra / Bai", category: "phrases" },
  { english: "carpet", garo: "Am", category: "uncategorized" },
  { english: "child", garo: "Degipa", category: "family" },
  { english: "cloud", garo: "Aram", category: "uncategorized" },
  { english: "coming", garo: "Re·baengjok", category: "verbs" },
  { english: "conversation", garo: "Agangrikani", category: "phrases" },
  { english: "country", garo: "A.song", category: "travel" },
  { english: "current", garo: "Da·o ong·enggipa", category: "uncategorized" },
  { english: "dangerous", garo: "Namen kenbegnigipa", category: "uncategorized" },
  { english: "decent", garo: "Kraa", category: "uncategorized" },
  { english: "decide", garo: "Tik ka·ani", category: "verbs" },
  { english: "depend", garo: "Pangchaka", category: "verbs" },
  { english: "dry fish", garo: "Na·kam", category: "food" },
  { english: "early", garo: "Seng·gnang", category: "uncategorized" },
  { english: "earn", garo: "Man·a", category: "business" },
  { english: "earthquake", garo: "Banggria", category: "uncategorized" },
  { english: "eaten", garo: "Cha·man·aha", category: "food" },
  { english: "echo", garo: "Gam·chak", category: "uncategorized" },
  { english: "educated", garo: "Skia man·gipa", category: "education" },
  { english: "eel", garo: "Na·nil", category: "animals" },
  { english: "eggshell", garo: "Do·chi bikrok", category: "animals" },
  { english: "elder", garo: "Dal·bata", category: "family" },
  { english: "electric", garo: "Karen", category: "uncategorized" },
  { english: "eyelash", garo: "Miksmil", category: "health" },
  { english: "eyebrows", garo: "Miksmil", category: "health" },
  { english: "face", garo: "Mikkang", category: "health" },
  { english: "first", garo: "Skang", category: "numbers" },
  { english: "flower", garo: "Bibal", category: "uncategorized" },
  { english: "foreigner", garo: "Ruri", category: "uncategorized" },
  { english: "go home", garo: "Nokchi re·bo", category: "travel" },
  { english: "going", garo: "Re·angengjok", category: "verbs" },
  { english: "hair", garo: "Kni", category: "health" },
  { english: "inheritance", garo: "Man·rikani", category: "business" },
  { english: "knowledgeable", garo: "Ui ma·sibegipa mande", category: "education" },
  { english: "last year", garo: "Da·sikkari", category: "uncategorized" },
  { english: "late", garo: "Ja·manchaka", category: "uncategorized" },
  { english: "laugh", garo: "Ka·dinga", category: "verbs" },
  { english: "mosquito", garo: "Ganggu", category: "animals" },
  { english: "mouth", garo: "Kusik", category: "health" },
  { english: "must", garo: "Nang.a", category: "uncategorized" },
  { english: "name", garo: "Bimung", category: "uncategorized" },
  { english: "nostril", garo: "Gingkol", category: "health" },
  { english: "nowadays", garo: "Da·ororo", category: "uncategorized" },
  { english: "okay", garo: "Am", category: "phrases" },
  { english: "once upon a time", garo: "Changsa·o", category: "phrases" },
  { english: "our", garo: "An.chingni", category: "uncategorized" },
  { english: "pair", garo: "Jora", category: "uncategorized" },
  { english: "pig", garo: "Wak", category: "animals" },
  { english: "pork", garo: "Wak be·en", category: "food" },
  { english: "priceless", garo: "Dam gri", category: "business" },
  { english: "puppy", garo: "Achak bisa", category: "animals" },
  { english: "queen", garo: "Rani", category: "uncategorized" },
  { english: "rainy", garo: "Mikka wabekbeka", category: "uncategorized" },
  { english: "reserve", garo: "Kange dona", category: "uncategorized" },
  { english: "rice powder", garo: "Pura", category: "food" },
  { english: "room", garo: "Kuturi", category: "uncategorized" },
  { english: "sad", garo: "Duk ong'a", category: "uncategorized" },
  { english: "said", garo: "Aganaha", category: "verbs" },
  { english: "saying", garo: "Aganenga", category: "verbs" },
  { english: "saw", garo: "Nikaha", category: "verbs" },
  { english: "scared", garo: "Kena", category: "uncategorized" },
  { english: "shameless", garo: "Mikil gri", category: "uncategorized" },
  { english: "shoe", garo: "Juta", category: "uncategorized" },
  { english: "speak", garo: "Agana", category: "verbs" },
  { english: "stand", garo: "Chakata", category: "verbs" },
  { english: "stop", garo: "Dondip", category: "verbs" },
  { english: "studying", garo: "Poraienga", category: "education" },
  { english: "reading", garo: "Poraienga", category: "education" },
  { english: "such as", garo: "Jekai", category: "uncategorized" },
  { english: "tea", garo: "Cha", category: "food" },
  { english: "teach", garo: "Skia", category: "education" },
  { english: "telling", garo: "Aganenga", category: "verbs" },
  { english: "their", garo: "Uamangni", category: "uncategorized" },
  { english: "thief", garo: "Cha·ugipa", category: "uncategorized" },
  { english: "thumb", garo: "Jaksi dalgipa", category: "health" },
  { english: "time", garo: "Somoi", category: "uncategorized" },
  { english: "town", garo: "Songjinma", category: "travel" },
  { english: "urgent", garo: "Bakan dakna nanggipa", category: "uncategorized" },
  { english: "video", garo: "Vidio", category: "uncategorized" },
  { english: "village", garo: "Song", category: "travel" },
  { english: "wake up", garo: "Chakatboha", category: "verbs" },
  { english: "wash", garo: "Su·gala", category: "verbs" },
  { english: "way", garo: "Rama", category: "travel" },
  { english: "younger sister", garo: "Nono", category: "family" },
];

const master = JSON.parse(fs.readFileSync('master_dictionary.json'));
const seen = new Set(master.map(e => (e.english||'').toLowerCase().trim() + '|' + (e.garo||'').toLowerCase().trim()));

let added = 0;
for (const entry of NEW_ENTRIES) {
  const key = entry.english.toLowerCase().trim() + '|' + entry.garo.toLowerCase().trim();
  if (!seen.has(key)) {
    master.push({ english: entry.english, garo: entry.garo, pos: null, category: entry.category, classifier: null, notes: null });
    seen.add(key);
    added++;
  }
}

console.log('Added:', added, '| Total:', master.length);
fs.writeFileSync('master_dictionary.json', JSON.stringify(master, null, 2));

const compiled = {};
for (const e of master) {
  const key = (e.english||'').toLowerCase().trim();
  if (!key || !e.garo) continue;
  if (!compiled[key]) compiled[key] = [];
  compiled[key].push({ garo: e.garo, pos: e.pos||null, category: e.category||'uncategorized', classifier: e.classifier||null });
}
fs.writeFileSync('src/compiled_dict.json', JSON.stringify(compiled));
console.log('compiled_dict rebuilt — keys:', Object.keys(compiled).length);
